https://www.springboard.com/blog/data-science/15-fun-datasets-to-analyze/
"Scammers use fake job posts to steal people’s identities by posting unusually enticing job descriptions, and then requiring applicants to provide their Social Security numbers and personal details upfront, ostensibly so they can be considered for an interview. This Kaggle dataset compiled by data scientist Shivam Bansal contains 18,000 job descriptions, of which about 800 are fake. The data consists of both textual information and meta-information about the job posts. You can use the data to create classification models to determine which job posts are fraudulent or real. "

https://www.kaggle.com/datasets/shivamb/real-or-fake-fake-jobposting-prediction/data

**Final Project**
Due May 7 by 11pm Points 100 Submitting a file upload File Types pdf Available until May 7 at 11:15pm
Up to this point, we have learned and discussed several machine learning algorithms. Now, it's time to put that knowledge into practice by applying these techniques to a problem of your own choosing. This could be any topic that sparks your interest!

To begin your project, consider areas you're passionate about, and look for publicly accessible datasets related to those interests.

You can explore the datasets/environments in Resources page under the Start Here module.

NOTE: The data or problem should be sufficiently complex, requiring a minimum of approximately 10,000 samples and at least 5 features.  In Data section, you should explicitly mention the size of data. 


The project requires a comprehensive machine learning pipeline, including: data exploration and analysis with appropriate visualizations; preprocessing (with explanations if not needed); selection of machine learning algorithms (at least two ML algorithms) with a rationale for each choice; and detailed observation and analysis of results, discussing whether the model performs as expected and identifying potential improvements.

* The bold face items above are key factors in determining your project grade.

**Submission**
**You are preparing a project report (pdf).  The recommended structure of the report contains:**

Cover page
- title
- name
  
Introduction

Data
- Introduce the data
- perform basic (visual) analysis
- Preprocessing
  
Methods
- details of your ML algorithms (at least two algorithms/models)
  
Results
- Explain detailed set up to solve the problem
- test your methods and show the results
- Discuss observation and analyze them
  
Conclusions
- conclude your work
- don't forget to mention what you have learned!
  
References
- It is important to cite others' work.
  
Acknowledgement
- if you use online resources and AI for your project, properly state them here how you use them. Check my slides for example acknowledgement.

Source Code
- Provide a GitHub link (make sure to be publicly accessible for grading)
  
**Use MLA style to cite and reference others work!**

# Using Machine Learning to Recongize Fake Job Postings

#### 1    Introduction
This is the final individual report for ITSC 3156.  My project's goal is to utilize machine learning to train a model to help individuals to recognize fake job postings. The code can be located on github:  https://github.com/


#### 1.1  Problem Statement
Fake job posting is a significant concern for students graduating from universities and experienced job seekers, leading to wasted time, potential financial crimes, and misplaced career goals.  The increasing number of fraudulent listings on online job platforms highlights the need for effective detection methods to protect applicants.


#### 1.2  Motivation 
The motivation for our study is to assist job seekers in making better decisions about whether a job listing is credible or fake by developing a binary classification model.  According to an article in the *Wall Street Journal*, these positions are referred to as ghost jobs - "roles that companies advertise but have no intention of filling" and they account for one in five job postings online (cook).  "A similar survey from Resume Builder finds 40% of hiring managers admitted posting fake job listings in the last year, and 70% of them viewed the practice as perfectly acceptable." (zizka) The author offers suggestions such as verifying the posting is no more than 60 to 90 days, verifying postings by applying directly at the company website, and networking to locate opportunities before they are posted. 


#### 1.2  Challenges
The primary challenges in this study include creating constructing a robust model that does not rely on token-based analysis and large-language models, as well as identifying alternative models for predicting the validity of job postings.   Addiitionally, the original dataset contained a significant number of features with missing values, including within subset of fake postings.


#### 1.3  Concise Summary
In our study, the Real / Fake Job Posting Prediction dataset contains 18,000 postings of which 800 are classified as fake. The dataset includes various features such as job id, job title/entry, location, department, salary range, company profile, description, requirements, benefits, telecommuting, has company logo (presence of company logo), has questions (screening questions), employment type, required experience, required education, industry, function, fraudulent indicator.  The data contains both textual and meta information related to job postings. It was preprocessed and split into training (80 percent) and testing (20 precent).

#### 2    Data / environment

In [5]:
import numpy as mp
import pandas as pd

In [6]:
jobs = pd.read_csv("fake_job_postings.csv")
jobs.head(4)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0

In [7]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [8]:
jobs.describe()

,job_id,telecommuting,has_company_logo,has_questions,fraudulent
count,17880.000000,17880.000000,17880.000000,17880.000000,17880.000000
mean,8940.500000,0.042897,0.795302,0.491723,0.048434
std,5161.655742,0.202631,0.403492,0.499945,0.214688
min,1.000000,0.000000,0.000000,0.000000,0.000000
25%,4470.750000,0.000000,1.000000,0.000000,0.000000
50%,8940.500000,0.000000,1.000000,0.000000,0.000000
75%,13410.250000,0.000000,1.000000,1.000000,0.000000
max,17880.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
jobs.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [16]:
jobs[jobs['fraudulent'] == 1].isnull().sum()

job_id                   0
title                    0
location                19
department             531
salary_range           643
company_profile        587
description              1
requirements           154
benefits               364
telecommuting            0
has_company_logo         0
has_questions            0
employment_type        241
required_experience    435
required_education     451
industry               275
function               337
fraudulent               0
dtype: int64

#### 2     Data

The Real / Fake Job Posting Prediction dataset contains 18,000 postings of which 800 are classified as fake. The dataset includes eighteen features such as job id, job title/entry, location, department, salary range, company profile, description, requirements, benefits, telecommuting, has company logo (presence of company logo), has questions (screening questions), employment type, required experience, required education, industry, function, fraudulent indicator.  The data contains both textual and meta information related to job postings. 

This dataset was downloaded from Kaggle (Shivam Bansal); however, documentation regarding its origin is unavailable.  The Kaggle page contains an acknowledgement to The University of the Aegean | Laboratory of Information & Communication Systems Security with a link; however, at the time of access, the link was down for service maintenance.

#### 2.1    Data visualization


#### 2.2    Data Analysis

#### 2.3    Data Preprocessing

After importing the dataset, we completed

#### 3      Methods


#### 3.1    algortithm 1

#### 3.2    algortithm 1

#### 4      Results

#### 4.1    Experimental Setup      


#### 4.2    Observations


#### 4.3    Anlaysis


#### 4.4    Experiments to Support Analysis

#### 5      Conclusions

Provide concluding remarks about the project (1-2 paragraphs)

Can discuss the following:
-Thoughts about the project
-What you have learned
-Challenges and how you overcome them

## References and Citations    Use MLA style to cite and reference others work! using MLA 8th edition
Works Cited

Cook, Lynn. Fake Job Postings are Becoming a Real Problem; One in Five Jobs Advertised is Fake Or Not Filled, According to a New Analysis; 'More Soul-Crushing than Ever'. Dow Jones &  Company Inc, New York, N.Y., 2025. ProQuest, https://www.proquest.com/blogs-podcasts-websites/fake-job-postings-are-becoming-real-problem-one/docview/3154515213/se-2.
https://www.proquest.com/blogs-podcasts-websites/fake-job-postings-are-becoming-real-problem-one/docview/3154515213/se-2?accountid=14605




Zizka, Tom. Fake Jobs Becoming growing problem for real Job Seekers. FOX 26 Houston, Houston, T.X., 2025.  https://www.fox26houston.com/news/fake-jobs-becoming-growing-problem-real-job-seekers
https://www.fox26houston.com/news/fake-jobs-becoming-growing-problem-real-job-seekers

## Acknowledgement

In [ ]:
Link to Source Code